version: '3.9'
services:
  taskflow-dev:
    build:
      context: ../../
      dockerfile: Docker/development/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ../../:/app
      - /app/node_modules
      - /app/.next
    env_file:
      - ../../.env
      
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true 
    restart: unless-stopped